project_id = "rjvgdqcbvikmjlrtraap"

[functions.zoho-availability-range]
verify_jwt = false

[functions.zoho-availability-day]
verify_jwt = false

[functions.zoho-book]
verify_jwt = false

[functions.zoho-test-simple]
verify_jwt = false

[functions.zoho-sync-availability]
verify_jwt = false

[functions.zoho-create-booking]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-staff-code]
verify_jwt = false
